### ISSUE TITLE
HIMEMX always reports "ignored commandline" and displays garbage when /MAX switch it used

### ISSUE THREAD

**Issue by zhro** [Baron-von-Riedesel/HimemX#3]
I am using HIMEMX with the /MAX switch to limit the available memory, as the 1GB that is installed causes problems for some programs. While using the /MAX switch does modify the available XMS memory, I always get an error "ignored commandline" and garbage output, sometimes with a system beep, when HIMEMX loads.

I tried both versions 3.36 and 3.37 of HIMEMX and HIMEMX2. This problem exists with both FreeDOS and MS-DOS 7.1 with nothing else in the CONFIG.SYS file and an empty AUTOEXEC.BAT file. I am using an Intel i950 motherboard.

I tried using the switch as:

/MAX=32678, /MAX=32678k, and /MAX=32678K.

![20221121_073710](https://user-images.githubusercontent.com/4738876/203059535-63d960ca-ad68-4fc5-a3a4-c04ff0de5ad6.jpg)

**Comment by Baron-von-Riedesel** [comment]
confirmed - I couldn't reproduce the garbage, but the stack was corrupted due to a wrong "prototype", which might easily have resulted in such an effect.

In the new release v.3.38 this should be fixed.

**Comment by zhro** [comment]
Thank you for the speedy response. The garbage is gone, but I still get the "ignored commandline" message with a bunch of spaces. The same issue occurs with NUMHANDLES.

![20221121_135252](https://user-images.githubusercontent.com/4738876/203136806-92f11c7c-c8f8-49ef-9c83-e4d84329e885.jpg)
![20221121_135245](https://user-images.githubusercontent.com/4738876/203136808-e4260fe8-6f22-4d46-8af2-4270702a79dd.jpg)

![Uploading 20221121_133650.jpg…]()

**Comment by zhro** [comment]
![20221121_133526](https://user-images.githubusercontent.com/4738876/203136996-c8f1e056-f426-4284-b670-4e1bb2f538b1.jpg)

**Comment by zhro** [comment]
Pictures from NUMHANDLES.

![20221121_133526](https://user-images.githubusercontent.com/4738876/203137165-c2c7fee1-c582-412c-8dd5-b7ea622d5515.jpg)

![20221121_133650](https://user-images.githubusercontent.com/4738876/203137163-7dbafcfe-9865-4118-9a50-5f5c3ccfc7d6.jpg)

**Comment by zhro** [comment]
Thank you for the speedy response! It seems to be fixed now. I also found this error with NUMHANDLES, but this appears to have been fixed now as well.
